#!/bin/bash
# Certificate generation script for Raspberry Pi Pico K3s node
# This generates the certificates needed for the Pico to authenticate with k3s

set -e

NODE_NAME="pico-node-1"
# Placeholder - will be updated with actual Pico IP after WiFi connection
NODE_IP="192.168.86.250"

# K3s certificate directories
CA_CERT="/var/lib/rancher/k3s/server/tls/client-ca.crt"
CA_KEY="/var/lib/rancher/k3s/server/tls/client-ca.key"
SERVER_CA_CERT="/var/lib/rancher/k3s/server/tls/server-ca.crt"
SERVER_CA_KEY="/var/lib/rancher/k3s/server/tls/server-ca.key"

# Output directory
OUT_DIR="/home/projects/k3s-device/k3s-pico-node/certs"

echo "Generating certificates for Pico node: ${NODE_NAME}"
echo "Node IP (placeholder): ${NODE_IP}"
echo "Output directory: ${OUT_DIR}"

# Generate client kubelet certificate (for authenticating TO API server)
echo ""
echo "1. Generating client kubelet certificate..."
openssl req -new -newkey rsa:2048 -nodes \
  -keyout ${OUT_DIR}/client-kubelet.key \
  -out ${OUT_DIR}/client-kubelet.csr \
  -subj "/CN=system:node:${NODE_NAME}/O=system:nodes"

sudo openssl x509 -req -in ${OUT_DIR}/client-kubelet.csr \
  -CA ${CA_CERT} -CAkey ${CA_KEY} \
  -CAcreateserial -out ${OUT_DIR}/client-kubelet.crt \
  -days 365 -sha256

# Generate serving kubelet certificate (for API server to connect TO kubelet)
echo ""
echo "2. Generating serving kubelet certificate..."
cat > ${OUT_DIR}/serving-kubelet.conf <<EOF
[req]
distinguished_name = req_distinguished_name
req_extensions = v3_req
prompt = no

[req_distinguished_name]
CN = ${NODE_NAME}

[v3_req]
keyUsage = digitalSignature, keyEncipherment
extendedKeyUsage = serverAuth
subjectAltName = @alt_names

[alt_names]
DNS.1 = ${NODE_NAME}
DNS.2 = localhost
IP.1 = 127.0.0.1
IP.2 = ${NODE_IP}
EOF

openssl req -new -newkey rsa:2048 -nodes \
  -keyout ${OUT_DIR}/serving-kubelet.key \
  -out ${OUT_DIR}/serving-kubelet.csr \
  -config ${OUT_DIR}/serving-kubelet.conf

sudo openssl x509 -req -in ${OUT_DIR}/serving-kubelet.csr \
  -CA ${SERVER_CA_CERT} -CAkey ${SERVER_CA_KEY} \
  -CAcreateserial -out ${OUT_DIR}/serving-kubelet.crt \
  -days 365 -sha256 -extensions v3_req \
  -extfile ${OUT_DIR}/serving-kubelet.conf

# Copy CA certificates
echo ""
echo "3. Copying CA certificates..."
sudo cp ${CA_CERT} ${OUT_DIR}/client-ca.crt
sudo cp ${SERVER_CA_CERT} ${OUT_DIR}/server-ca.crt

# Fix ownership
sudo chown -R ${USER}:${USER} ${OUT_DIR}

# Convert to C header file
echo ""
echo "4. Converting certificates to C header file..."
cat > ${OUT_DIR}/certs.h <<'HEADER_START'
// Auto-generated certificates for Raspberry Pi Pico K3s node
// Generated by generate-certs.sh
#ifndef CERTS_H
#define CERTS_H

HEADER_START

echo "// Client CA Certificate" >> ${OUT_DIR}/certs.h
echo "const char client_ca_cert[] = " >> ${OUT_DIR}/certs.h
awk '{print "\"" $0 "\\n\""}' ${OUT_DIR}/client-ca.crt >> ${OUT_DIR}/certs.h
echo ";" >> ${OUT_DIR}/certs.h
echo "" >> ${OUT_DIR}/certs.h

echo "// Client Kubelet Certificate" >> ${OUT_DIR}/certs.h
echo "const char client_kubelet_cert[] = " >> ${OUT_DIR}/certs.h
awk '{print "\"" $0 "\\n\""}' ${OUT_DIR}/client-kubelet.crt >> ${OUT_DIR}/certs.h
echo ";" >> ${OUT_DIR}/certs.h
echo "" >> ${OUT_DIR}/certs.h

echo "// Client Kubelet Private Key" >> ${OUT_DIR}/certs.h
echo "const char client_kubelet_key[] = " >> ${OUT_DIR}/certs.h
awk '{print "\"" $0 "\\n\""}' ${OUT_DIR}/client-kubelet.key >> ${OUT_DIR}/certs.h
echo ";" >> ${OUT_DIR}/certs.h
echo "" >> ${OUT_DIR}/certs.h

echo "// Server CA Certificate" >> ${OUT_DIR}/certs.h
echo "const char server_ca_cert[] = " >> ${OUT_DIR}/certs.h
awk '{print "\"" $0 "\\n\""}' ${OUT_DIR}/server-ca.crt >> ${OUT_DIR}/certs.h
echo ";" >> ${OUT_DIR}/certs.h
echo "" >> ${OUT_DIR}/certs.h

echo "// Serving Kubelet Certificate" >> ${OUT_DIR}/certs.h
echo "const char serving_kubelet_cert[] = " >> ${OUT_DIR}/certs.h
awk '{print "\"" $0 "\\n\""}' ${OUT_DIR}/serving-kubelet.crt >> ${OUT_DIR}/certs.h
echo ";" >> ${OUT_DIR}/certs.h
echo "" >> ${OUT_DIR}/certs.h

echo "// Serving Kubelet Private Key" >> ${OUT_DIR}/certs.h
echo "const char serving_kubelet_key[] = " >> ${OUT_DIR}/certs.h
awk '{print "\"" $0 "\\n\""}' ${OUT_DIR}/serving-kubelet.key >> ${OUT_DIR}/certs.h
echo ";" >> ${OUT_DIR}/certs.h
echo "" >> ${OUT_DIR}/certs.h

echo "#endif // CERTS_H" >> ${OUT_DIR}/certs.h

echo ""
echo "✓ Certificate generation complete!"
echo "✓ Certificates saved in: ${OUT_DIR}/"
echo "✓ C header file: ${OUT_DIR}/certs.h"
echo ""
echo "Certificate files:"
ls -lh ${OUT_DIR}/*.{crt,key} 2>/dev/null || true
